// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blogProtos.proto

package com.milo.server.beans;

public final class BlogProtos {
  private BlogProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum BlogType
      implements com.google.protobuf.ProtocolMessageEnum {
    Technic(0, 0),
    Essay(1, 1),
    Other(2, 2),
    ;
    
    public static final int Technic_VALUE = 0;
    public static final int Essay_VALUE = 1;
    public static final int Other_VALUE = 2;
    
    
    public final int getNumber() { return value; }
    
    public static BlogType valueOf(int value) {
      switch (value) {
        case 0: return Technic;
        case 1: return Essay;
        case 2: return Other;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<BlogType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<BlogType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BlogType>() {
            public BlogType findValueByNumber(int number) {
              return BlogType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.milo.server.beans.BlogProtos.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final BlogType[] VALUES = {
      Technic, Essay, Other, 
    };
    
    public static BlogType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private BlogType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:ProtoJs.Blog.BlogType)
  }
  
  public interface BlogOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int64 id = 1;
    boolean hasId();
    long getId();
    
    // optional string title = 2;
    boolean hasTitle();
    String getTitle();
    
    // optional string brief = 3;
    boolean hasBrief();
    String getBrief();
    
    // optional int64 timestamp = 4;
    boolean hasTimestamp();
    long getTimestamp();
    
    // optional int32 review = 5;
    boolean hasReview();
    int getReview();
    
    // optional string content = 6;
    boolean hasContent();
    String getContent();
    
    // optional .ProtoJs.Blog.BlogType blogType = 7 [default = Technic];
    boolean hasBlogType();
    com.milo.server.beans.BlogProtos.BlogType getBlogType();
  }
  public static final class Blog extends
      com.google.protobuf.GeneratedMessage
      implements BlogOrBuilder {
    // Use Blog.newBuilder() to construct.
    private Blog(Builder builder) {
      super(builder);
    }
    private Blog(boolean noInit) {}
    
    private static final Blog defaultInstance;
    public static Blog getDefaultInstance() {
      return defaultInstance;
    }
    
    public Blog getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.milo.server.beans.BlogProtos.internal_static_ProtoJs_Blog_Blog_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.milo.server.beans.BlogProtos.internal_static_ProtoJs_Blog_Blog_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getId() {
      return id_;
    }
    
    // optional string title = 2;
    public static final int TITLE_FIELD_NUMBER = 2;
    private Object title_;
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTitle() {
      Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          title_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTitleBytes() {
      Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string brief = 3;
    public static final int BRIEF_FIELD_NUMBER = 3;
    private Object brief_;
    public boolean hasBrief() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getBrief() {
      Object ref = brief_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          brief_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getBriefBytes() {
      Object ref = brief_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        brief_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 timestamp = 4;
    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getTimestamp() {
      return timestamp_;
    }
    
    // optional int32 review = 5;
    public static final int REVIEW_FIELD_NUMBER = 5;
    private int review_;
    public boolean hasReview() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getReview() {
      return review_;
    }
    
    // optional string content = 6;
    public static final int CONTENT_FIELD_NUMBER = 6;
    private Object content_;
    public boolean hasContent() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          content_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .ProtoJs.Blog.BlogType blogType = 7 [default = Technic];
    public static final int BLOGTYPE_FIELD_NUMBER = 7;
    private com.milo.server.beans.BlogProtos.BlogType blogType_;
    public boolean hasBlogType() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public com.milo.server.beans.BlogProtos.BlogType getBlogType() {
      return blogType_;
    }
    
    private void initFields() {
      id_ = 0L;
      title_ = "";
      brief_ = "";
      timestamp_ = 0L;
      review_ = 0;
      content_ = "";
      blogType_ = com.milo.server.beans.BlogProtos.BlogType.Technic;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getBriefBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, timestamp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, review_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getContentBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeEnum(7, blogType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getBriefBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, timestamp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, review_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getContentBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, blogType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.milo.server.beans.BlogProtos.Blog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.milo.server.beans.BlogProtos.Blog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.milo.server.beans.BlogProtos.Blog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.milo.server.beans.BlogProtos.Blog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.milo.server.beans.BlogProtos.Blog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.milo.server.beans.BlogProtos.Blog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.milo.server.beans.BlogProtos.Blog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.milo.server.beans.BlogProtos.Blog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.milo.server.beans.BlogProtos.Blog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.milo.server.beans.BlogProtos.Blog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.milo.server.beans.BlogProtos.Blog prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.milo.server.beans.BlogProtos.BlogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.milo.server.beans.BlogProtos.internal_static_ProtoJs_Blog_Blog_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.milo.server.beans.BlogProtos.internal_static_ProtoJs_Blog_Blog_fieldAccessorTable;
      }
      
      // Construct using com.milo.server.beans.BlogProtos.Blog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        brief_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        review_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        blogType_ = com.milo.server.beans.BlogProtos.BlogType.Technic;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.milo.server.beans.BlogProtos.Blog.getDescriptor();
      }
      
      public com.milo.server.beans.BlogProtos.Blog getDefaultInstanceForType() {
        return com.milo.server.beans.BlogProtos.Blog.getDefaultInstance();
      }
      
      public com.milo.server.beans.BlogProtos.Blog build() {
        com.milo.server.beans.BlogProtos.Blog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.milo.server.beans.BlogProtos.Blog buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.milo.server.beans.BlogProtos.Blog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.milo.server.beans.BlogProtos.Blog buildPartial() {
        com.milo.server.beans.BlogProtos.Blog result = new com.milo.server.beans.BlogProtos.Blog(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.brief_ = brief_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.review_ = review_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.blogType_ = blogType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.milo.server.beans.BlogProtos.Blog) {
          return mergeFrom((com.milo.server.beans.BlogProtos.Blog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.milo.server.beans.BlogProtos.Blog other) {
        if (other == com.milo.server.beans.BlogProtos.Blog.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasBrief()) {
          setBrief(other.getBrief());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasReview()) {
          setReview(other.getReview());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        if (other.hasBlogType()) {
          setBlogType(other.getBlogType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              title_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              brief_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              timestamp_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              review_ = input.readInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              content_ = input.readBytes();
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
              com.milo.server.beans.BlogProtos.BlogType value = com.milo.server.beans.BlogProtos.BlogType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(7, rawValue);
              } else {
                bitField0_ |= 0x00000040;
                blogType_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int64 id = 1;
      private long id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getId() {
        return id_;
      }
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string title = 2;
      private Object title_ = "";
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTitle() {
        Object ref = title_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTitle(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      void setTitle(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
      }
      
      // optional string brief = 3;
      private Object brief_ = "";
      public boolean hasBrief() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getBrief() {
        Object ref = brief_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          brief_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setBrief(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        brief_ = value;
        onChanged();
        return this;
      }
      public Builder clearBrief() {
        bitField0_ = (bitField0_ & ~0x00000004);
        brief_ = getDefaultInstance().getBrief();
        onChanged();
        return this;
      }
      void setBrief(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        brief_ = value;
        onChanged();
      }
      
      // optional int64 timestamp = 4;
      private long timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000008;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int32 review = 5;
      private int review_ ;
      public boolean hasReview() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getReview() {
        return review_;
      }
      public Builder setReview(int value) {
        bitField0_ |= 0x00000010;
        review_ = value;
        onChanged();
        return this;
      }
      public Builder clearReview() {
        bitField0_ = (bitField0_ & ~0x00000010);
        review_ = 0;
        onChanged();
        return this;
      }
      
      // optional string content = 6;
      private Object content_ = "";
      public boolean hasContent() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setContent(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        content_ = value;
        onChanged();
        return this;
      }
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000020);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      void setContent(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        content_ = value;
        onChanged();
      }
      
      // optional .ProtoJs.Blog.BlogType blogType = 7 [default = Technic];
      private com.milo.server.beans.BlogProtos.BlogType blogType_ = com.milo.server.beans.BlogProtos.BlogType.Technic;
      public boolean hasBlogType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public com.milo.server.beans.BlogProtos.BlogType getBlogType() {
        return blogType_;
      }
      public Builder setBlogType(com.milo.server.beans.BlogProtos.BlogType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        blogType_ = value;
        onChanged();
        return this;
      }
      public Builder clearBlogType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        blogType_ = com.milo.server.beans.BlogProtos.BlogType.Technic;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ProtoJs.Blog.Blog)
    }
    
    static {
      defaultInstance = new Blog(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ProtoJs.Blog.Blog)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoJs_Blog_Blog_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtoJs_Blog_Blog_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020blogProtos.proto\022\014ProtoJs.Blog\"\227\001\n\004Blo" +
      "g\022\n\n\002id\030\001 \001(\003\022\r\n\005title\030\002 \001(\t\022\r\n\005brief\030\003 " +
      "\001(\t\022\021\n\ttimestamp\030\004 \001(\003\022\016\n\006review\030\005 \001(\005\022\017" +
      "\n\007content\030\006 \001(\t\0221\n\010blogType\030\007 \001(\0162\026.Prot" +
      "oJs.Blog.BlogType:\007Technic*-\n\010BlogType\022\013" +
      "\n\007Technic\020\000\022\t\n\005Essay\020\001\022\t\n\005Other\020\002B\027\n\025com" +
      ".milo.server.beans"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ProtoJs_Blog_Blog_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ProtoJs_Blog_Blog_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProtoJs_Blog_Blog_descriptor,
              new java.lang.String[] { "Id", "Title", "Brief", "Timestamp", "Review", "Content", "BlogType", },
              com.milo.server.beans.BlogProtos.Blog.class,
              com.milo.server.beans.BlogProtos.Blog.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
